apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wanderlust
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kmvishal/wanderlust-frontend:v2.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  namespace: wanderlust
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
    nodePort: 31000
