apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-storage  # ✅ Changed from "mongo-storage" to "redis-storage"
            mountPath: /data  # ✅ Standard Redis data directory
      volumes:
        - name: redis-storage  # ✅ Matching volume name
          emptyDir: {}  # ✅ Temporary storage (use PVC if needed)

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service  # ✅ Fixed the typo
  namespace: wanderlust
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
